---
metrics:
- name: examples_global_value
  path: "{ .redis }"
  help: Example of a top-level global value scrape in the json
  labels:
    environment: beta # static label
    location: "{.redis}"  
  values:
    active: 1        # dynamic label
- name: mysql_status
  path: "{ .mysql }"
  help: Example of a top-level global value scrape in the json
  labels:
    mysql: "{.mysql}"  
  values:
    active: 1 

headers:
  X-Dummy: my-test-header

# For full http client config parameters, ref: https://pkg.go.dev/github.com/prometheus/common/config?tab=doc#HTTPClientConfig
#
# http_client_config:
#   tls_config:
#     insecure_skip_verify: true
#   basic_auth:
#     username: myuser
#     #password: veryverysecret
#     password_file: /tmp/mysecret.txt
